version: '3'
services:
  app:
    build: .
    container_name: app
    volumes:
      -  ./:/home/app
    ports:
      - "8022:8082"
  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      -  db_data:/var/lib/mysql
    restart: always
    ports:
      -  "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: fm
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123

volumes:
  db_data: {}

networks:
  net:
