admin:
  path: /admin
  controller: App\Controller\AdminController

countries:
  path: /countries
  controller: App\Controller\Country\ListController

addCountry:
  path: /addCountry
  controller: App\Controller\Country\AddController

editCountry:
  path: /editCountry/{id}
  controller: App\Controller\Country\EditController

deleteCountry:
  path: /deleteCountry/{id}
  controller: App\Controller\Country\DeleteCountry

fetchCountries:
  path: fetch-countries
  controller: App\Controller\RapidAPI\CountryController
